esphome:
  name: water-meter

esp8266:
  board: esp01

logger:

web_server:

api:

ota:
  password: $ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Water Meter Hotspot"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO0
    echo_pin: GPIO2
    name: "Ultrasonic Sensor"
    